# 這是放在個人專案根目錄下的 profiles.yml
bq_dbt_analytics:
  target: dev

  outputs:
    dev:
      type: bigquery
      method: oauth
      project: stock-backtest-491815
      dataset: stock_analytics_dev
      location: asia-east1
      threads: 4

    prod:
      type: bigquery
      method: oauth
      project: stock-backtest-491815
      dataset: stock_analytics
      location: asia-east1
      threads: 4